# Generated by Django 4.2 on 2023-04-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Normdoctors',
            fields=[
                ('doc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(blank=True, max_length=20, null=True)),
                ('doc_age', models.IntegerField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=20, null=True)),
                ('normdoctorscol1', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('mr_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'normdoctors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Normmedrec',
            fields=[
                ('mr_no', models.IntegerField(db_column='MR_No', primary_key=True, serialize=False)),
                ('treatment', models.CharField(blank=True, db_column='Treatment', max_length=20, null=True)),
                ('wbc_count', models.IntegerField(blank=True, db_column='WBC_Count', null=True)),
                ('blood_group', models.CharField(blank=True, db_column='Blood_Group', max_length=10, null=True)),
                ('height', models.IntegerField(blank=True, db_column='Height', null=True)),
                ('weight', models.IntegerField(blank=True, db_column='Weight', null=True)),
                ('doc_id', models.IntegerField(blank=True, db_column='Doc_ID', null=True)),
                ('patient_id', models.IntegerField(blank=True, db_column='Patient_ID', null=True)),
            ],
            options={
                'db_table': 'normmedrec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Normpatients',
            fields=[
                ('patient_id', models.IntegerField(db_column='Patient_ID', primary_key=True, serialize=False)),
                ('p_name', models.CharField(blank=True, db_column='P_Name', max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=10, null=True)),
                ('phone_no', models.FloatField(blank=True, db_column='Phone_No', null=True)),
                ('room_id', models.IntegerField(blank=True, db_column='Room_ID', null=True)),
                ('reg_id', models.IntegerField(blank=True, db_column='Reg_ID', null=True)),
                ('pres_id', models.IntegerField(blank=True, db_column='Pres_ID', null=True)),
                ('bill_id', models.IntegerField(blank=True, db_column='Bill_ID', null=True)),
                ('mr_no', models.IntegerField(blank=True, db_column='MR_No', null=True)),
                ('doc_id', models.IntegerField(blank=True, db_column='Doc_ID', null=True)),
            ],
            options={
                'db_table': 'normpatients',
                'managed': False,
            },
        ),
    ]
